[package]
name = "cuniforbits"
version = "0.1.0"
authors = ["Asa Zeren <asaizeren@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"